name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgis/postgis:10-2.5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
          PGUSER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 30s
          --health-retries 10
          --health-start-period 2s
    env:
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: password
      PAGER: cat
      DATE: 2017-05-19

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install Python requirements
        run: |
          pip install wheel
          pip install -r requirements.txt

      - run: make init

      - name: Run commands
        run: |
          make download
          make alerts
          make positions
          make tripupdates

      - name: Check on results
        run: |
          psql -c "SELECT * FROM rt.vehicle_positions LIMIT 10"
          psql -c "SELECT * FROM rt.trip_updates LIMIT 10"
          psql -c "SELECT * FROM rt.alerts LIMIT 10"
